export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const IS_AUTH = 'IS_AUTH';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const CARGANDO = 'CARGANDO';

export const SET_DATA = "SET_DATA";
export const CLEAR_DATA = "CLEAR_DATA";


export const SET_DONATION_CONFIG = "SET_DONATION_CONFIG"; 
export const CARGAR_HECHOS = "CARGAR_HECHOS"; 
export const HECHOS_CARGADOS = "HECHOS_CARGADOS"; 
export const ERROR_CARGAR_HECHOS = "ERROR_CARGAR_HECHOS"; 
export const SET_REPORTES_DATA = "SET_REPORTES_DATA";

export const CARGAR_HECHOS_NUEVOS = "CARGAR_HECHOS_NUEVOS"

export const SET_SUSCRIPCIONES = "SET_SUSCRIPCIONES"

export const SET_USUARIOS = "SET_USUARIOS";

