export const CARGANDO = 'CARGANDO';
export const OBTENER_CARRERAS = 'OBTENER_CARRERAS';
export const OBTENER_CARRERAS_SIS = 'OBTENER_CARRERAS_SIS';
export const OBTENER_CARRERAS_HABILITADO = 'OBTENER_CARRERAS_HABILITADO';